import {
  Activity,
  BadgeDollarSign,
  BarChart3,
  Boxes,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  Cog,
  Factory,
  FileBadge,
  FileStack,
  FileText,
  HandCoins,
  HardHat,
  Landmark,
  PackageCheck,
  QrCode,
  Settings,
  ShieldCheck,
  ShoppingCart,
  UserCog,
  Users,
  Wrench,
} from "lucide-react";
import type {
  IndustrialModule,
} from "@/types/industrial";

export const industrialModules: IndustrialModule[] = [
  {
    key: "dashboard",
    title: "Dashboard Executivo",
    description: "BI industrial em tempo real para diretoria, PCP e fabrica.",
    href: "/",
    icon: BarChart3,
    group: "Gestao",
    accent: "#003D7A",
  },
  {
    key: "comercial",
    title: "Comercial",
    description: "Pipeline, propostas, clientes e conversao de oportunidades.",
    href: "/comercial",
    icon: BriefcaseBusiness,
    group: "Receita",
    accent: "#0E7490",
  },
  {
    key: "orcamentos",
    title: "Orcamentos",
    description: "Orcamentos tecnicos com custos, margem, anexos e aprovacao.",
    href: "/orcamentos",
    icon: FileText,
    group: "Receita",
    accent: "#003D7A",
  },
  {
    key: "vendas",
    title: "Vendas",
    description: "Pedidos aprovados com geracao automatica de O.S.",
    href: "/vendas",
    icon: HandCoins,
    group: "Receita",
    accent: "#15803D",
  },
  {
    key: "engenharia",
    title: "Engenharia",
    description: "Fichas tecnicas, desenhos, revisoes e roteiros fabris.",
    href: "/engenharia",
    icon: Wrench,
    group: "Industrial",
    accent: "#334155",
  },
  {
    key: "estrutura-produto",
    title: "Estrutura de Produto",
    description: "BOM, materiais, operacoes, tempos padrao e revisoes.",
    href: "/estrutura-produto",
    icon: FileStack,
    group: "Industrial",
    accent: "#475569",
  },
  {
    key: "producao",
    title: "Producao",
    description: "Ordens, apontamentos, setores, tempos e rastreabilidade.",
    href: "/producao",
    icon: Factory,
    group: "Fabrica",
    accent: "#003D7A",
  },
  {
    key: "pcp",
    title: "PCP",
    description: "Sequenciamento, carga maquina, capacidade e prazos.",
    href: "/pcp",
    icon: CalendarClock,
    group: "Fabrica",
    accent: "#7C3AED",
  },
  {
    key: "fluxo-producao",
    title: "Fluxo de Producao",
    description: "Kanban industrial por setor com SLA, gargalos e prioridade.",
    href: "/fluxo-producao",
    icon: Activity,
    group: "Fabrica",
    accent: "#EA580C",
  },
  {
    key: "estoque",
    title: "Estoque",
    description: "Materiais inox, lotes, reservas, consumo automatico e inventario.",
    href: "/estoque",
    icon: Boxes,
    group: "Suprimentos",
    accent: "#0369A1",
  },
  {
    key: "compras",
    title: "Compras",
    description: "Solicitacoes, cotacoes, pedidos e fornecedores homologados.",
    href: "/compras",
    icon: ShoppingCart,
    group: "Suprimentos",
    accent: "#0F766E",
  },
  {
    key: "financeiro",
    title: "Financeiro",
    description: "Pagar, receber, fluxo de caixa, DRE, PIX, boletos e centros de custo.",
    href: "/financeiro",
    icon: Landmark,
    group: "Administrativo",
    accent: "#15803D",
  },
  {
    key: "rh",
    title: "RH",
    description: "Operadores, equipes, jornada, qualificacoes e produtividade.",
    href: "/rh",
    icon: HardHat,
    group: "Administrativo",
    accent: "#B45309",
  },
  {
    key: "qualidade",
    title: "Qualidade",
    description: "Inspecoes, nao conformidades, retrabalho e checklist final.",
    href: "/qualidade",
    icon: ClipboardCheck,
    group: "Industrial",
    accent: "#BE123C",
  },
  {
    key: "assistencia-tecnica",
    title: "Assistencia Tecnica",
    description: "Chamados, garantias, manutencao e historico de atendimento.",
    href: "/assistencia-tecnica",
    icon: PackageCheck,
    group: "Pos-venda",
    accent: "#0891B2",
  },
  {
    key: "etiquetas",
    title: "Etiquetas",
    description: "QR Code, codigo de barras, lote, setor atual e impressao Zebra/Epson.",
    href: "/etiquetas",
    icon: QrCode,
    group: "Fabrica",
    accent: "#003D7A",
  },
  {
    key: "usuarios-permissoes",
    title: "Usuarios e Permissoes",
    description: "JWT, perfis, auditoria, logs e permissoes por modulo.",
    href: "/usuarios-permissoes",
    icon: ShieldCheck,
    group: "Sistema",
    accent: "#1D4ED8",
  },
  {
    key: "setores",
    title: "Gestao de Setores",
    description: "Gerenciamento de departamentos, equipes e estrutura organizacional.",
    href: "/sistema/setores",
    icon: Building2,
    group: "Sistema",
    accent: "#7C3AED",
  },
  {
    key: "permissoes-usuario",
    title: "Permissoes por Usuario",
    description: "Gestao granular de permissoes individuais por usuario.",
    href: "/sistema/permissoes-usuario",
    icon: UserCog,
    group: "Sistema",
    accent: "#BE123C",
  },
  {
    key: "permissoes-setor",
    title: "Permissoes por Setor",
    description: "Gestao de permissoes por departamento/setor.",
    href: "/sistema/permissoes-setor",
    icon: ShieldCheck,
    group: "Sistema",
    accent: "#0891B2",
  },
  {
    key: "configuracoes",
    title: "Configuracoes",
    description: "Parametros industriais, setores, impostos, integracoes e SLA.",
    href: "/configuracoes",
    icon: Settings,
    group: "Sistema",
    accent: "#475569",
  },
];


