services:
  - type: web
    name: erp-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_R8MfSTaCjQA7@ep-nameless-smoke-aqassije-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
