kind = "web"
previewPath = "/"
title = "Sistema OS"
version = "1.0.0"
id = "artifacts/sistema-os"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22486

[services.development]
run = "pnpm --filter @workspace/sistema-os run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sistema-os", "run", "build" ]
publicDir = "artifacts/sistema-os/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22486"
BASE_PATH = "/"
